
import type { QualitySystemDocument } from '@/types';

export const qualitySystemDocuments: QualitySystemDocument[] = [
  // LEVEL A
  { docId: 'QM-001', title: 'Quality Manual – Euro Metal CNC Machining', level: 'A', relevantClauses: '4, 5 (Overall QMS)', docType: 'manual', filePath: '/docs/placeholder.txt' },
  { docId: 'POL-001', title: 'Quality Policy Statement', level: 'A', relevantClauses: '5.2', docType: 'policy', filePath: '/docs/placeholder.txt' },
  { docId: 'POL-002', title: 'Ethical Conduct & Product-Safety Policy', level: 'A', relevantClauses: '7.3, 8.1.3', docType: 'policy', filePath: '/docs/placeholder.txt' },
  { docId: 'POL-003', title: 'Communication Policy', level: 'A', relevantClauses: '7.4', docType: 'policy', filePath: '/docs/placeholder.txt' },
  { docId: 'POL-004', title: 'Safety Management Policy', level: 'A', relevantClauses: '8.1.3', docType: 'policy', filePath: '/docs/placeholder.txt' },

  // LEVEL B
  { docId: 'QP-420', title: 'Context & QMS Scope Procedure', level: 'B', relevantClauses: '4.1, 4.2, 4.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-440', title: 'QMS Process Definition and Interaction', level: 'B', relevantClauses: '4.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-430', title: 'Control of Documented Information', level: 'B', relevantClauses: '7.5', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-510', title: 'Leadership, Roles & Authority', level: 'B', relevantClauses: '5.1, 5.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-612', title: 'Risk & Opportunity Management', level: 'B', relevantClauses: '6.1, 8.1.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-620', title: 'Quality Objectives & KPI Deployment', level: 'B', relevantClauses: '6.2, 9.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-630', title: 'Change-Management Procedure', level: 'B', relevantClauses: '6.3, 8.5.6', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-710', title: 'Resource & Infrastructure Control', level: 'B', relevantClauses: '7.1.1, 7.1.2, 7.1.3, 7.1.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-712', title: 'Equipment Maintenance Management', level: 'B', relevantClauses: '7.1.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-715', title: 'Calibration & Measurement Traceability', level: 'B', relevantClauses: '7.1.5', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-716', title: 'Organizational Knowledge Management', level: 'B', relevantClauses: '7.1.6', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-717', title: 'Measurement System Analysis', level: 'B', relevantClauses: '7.1.5', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-720', title: 'Competence, Training & Awareness', level: 'B', relevantClauses: '7.2, 7.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-730', title: 'Internal / External Communication', level: 'B', relevantClauses: '7.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-740', title: 'Configuration Management', level: 'B', relevantClauses: '8.1.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-810', title: 'Customer Communication & Contract Review', level: 'B', relevantClauses: '8.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-815', title: 'Work Transfer Control', level: 'B', relevantClauses: '8.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-820', title: 'Purchasing & Supplier Approval', level: 'B', relevantClauses: '8.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-822', title: 'Supplier Performance Monitoring', level: 'B', relevantClauses: '8.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-825', title: 'Production Planning & Control', level: 'B', relevantClauses: '8.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-831', title: 'Validation of Special Processes', level: 'B', relevantClauses: '8.5.1.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-832', title: 'Counterfeit Part Prevention', level: 'B', relevantClauses: '8.1.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-840', title: 'Identification & Traceability', level: 'B', relevantClauses: '8.5.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-842', title: 'FOD Prevention & Cleanliness Control', level: 'B', relevantClauses: '8.5.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-845', title: 'Project Management', level: 'B', relevantClauses: '8.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-850', title: 'Preservation, Storage & Packaging', level: 'B', relevantClauses: '8.5.4', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-851', title: 'Control of Production and Service Provision', level: 'B', relevantClauses: '8.5.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-852', title: 'First Article Inspection (FAI)', level: 'B', relevantClauses: '8.5.1.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-853', title: 'Control of Customer & External Provider Property', level: 'B', relevantClauses: '8.5.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-855', title: 'Post-Delivery Activities Management', level: 'B', relevantClauses: '8.5.5', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-858', title: 'Software Validation Management', level: 'B', relevantClauses: '7.1.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-860', title: 'Final Inspection & Product Release', level: 'B', relevantClauses: '8.6', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-870', title: 'Non-conforming Output & Disposition', level: 'B', relevantClauses: '8.7', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-900', title: 'Monitoring, Measurement & Data Analysis', level: 'B', relevantClauses: '9.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-920', title: 'Internal Audit Procedure', level: 'B', relevantClauses: '9.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-930', title: 'Management Review Procedure', level: 'B', relevantClauses: '9.3', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-950', title: 'Corrective Action & Root-Cause Analysis', level: 'B', relevantClauses: '10.2', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-952', title: 'Human Factors Consideration Procedure', level: 'B', relevantClauses: '10.2.1.b', docType: 'procedure', filePath: '/docs/placeholder.txt' },
  { docId: 'QP-960', title: 'Continual-Improvement Framework', level: 'B', relevantClauses: '10.3, 10.1', docType: 'procedure', filePath: '/docs/placeholder.txt' },

  // LEVEL C
  { docId: 'WI-712-001', title: 'Preventive Maintenance for CNC Machines', level: 'C', relevantClauses: '7.1.3', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-712-002', title: 'Maintenance Schedule Planning', level: 'C', relevantClauses: '7.1.3', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-715-001', title: 'CMM Operation & Calibration Routine', level: 'C', relevantClauses: '7.1.5', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-715-002', title: 'Gage R&R Study Method', level: 'C', relevantClauses: '7.1.5', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-715-003', title: 'Hand Tool Verification & Calibration', level: 'C', relevantClauses: '7.1.5', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-720-001', title: 'New Employee Orientation Training', level: 'C', relevantClauses: '7.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-720-002', title: 'Training Effectiveness Evaluation', level: 'C', relevantClauses: '7.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-720-003', title: 'Operator Qualification for 5-Axis Machines', level: 'C', relevantClauses: '7.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-720-004', title: 'Quality Inspector Qualification', level: 'C', relevantClauses: '7.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-831-001', title: 'Heat-Treatment Purchase & Certification Check', level: 'C', relevantClauses: '8.4, 8.5.1.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-831-002', title: 'Anodizing/Plating Purchase & Certification Check', level: 'C', relevantClauses: '8.4, 8.5.1.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-831-003', title: 'NDT Purchase & Certification Check', level: 'C', relevantClauses: '8.4, 8.5.1.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-840-001', title: 'Part Marking & Serialization Method', level: 'C', relevantClauses: '8.5.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-842-001', title: 'FOD Prevention Practices for Production', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-842-002', title: 'Shop Floor Cleanliness Standards', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-850-001', title: 'Material Handling & Storage', level: 'C', relevantClauses: '8.5.4', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-850-002', title: 'Vacuum-Packing of Aluminium Parts', level: 'C', relevantClauses: '8.5.4', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-001', title: 'CNC Machine Setup & Zero-Point Verification', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-002', title: 'Tooling Selection & Life Management', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-003', title: 'CNC Program Management and Validation', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-004', title: 'Equipment and Software Validation', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-005', title: 'Standard Machining Operations', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-851-006', title: 'Complex Machining Operations', level: 'C', relevantClauses: '8.5.1', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-852-001', title: 'FAI Process & Report Completion', level: 'C', relevantClauses: '8.5.1.3', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-860-001', title: 'Visual Inspection Methods', level: 'C', relevantClauses: '8.6', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-860-002', title: 'Dimensional Inspection Methods', level: 'C', relevantClauses: '8.6', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-860-003', title: 'Surface Roughness Inspection', level: 'C', relevantClauses: '8.6', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-860-004', title: 'Product Test Methods', level: 'C', relevantClauses: '8.6', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-870-001', title: 'Non-conformance Handling & Segregation', level: 'C', relevantClauses: '8.7', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-950-001', title: 'Root Cause Analysis Methods', level: 'C', relevantClauses: '10.2', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },
  { docId: 'WI-952-001', title: 'Human Factors Assessment', level: 'C', relevantClauses: '10.2.1.b', docType: 'workInstruction', filePath: '/docs/placeholder.txt' },

  // LEVEL D1 - Continuous Logs
  { docId: 'FRM-420-001', title: 'Interested Party Register', level: 'D1', relevantClauses: '4.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-612-001', title: 'Risk Assessment & Mitigation Log', level: 'D1', relevantClauses: '6.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-712-001', title: 'Equipment Maintenance Log', level: 'D1', relevantClauses: '7.1.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-712-002', title: 'Preventive Maintenance Schedule', level: 'D1', relevantClauses: '7.1.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-712-003', title: 'Machine Downtime Log', level: 'D1', relevantClauses: '7.1.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-715-001', title: 'Measurement Equipment Register', level: 'D1', relevantClauses: '7.1.5', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-715-002', title: 'Calibration Certificate Log', level: 'D1', relevantClauses: '7.1.5', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-716-001', title: 'Lessons Learned Register / Knowledge Base Record', level: 'D1', relevantClauses: '7.1.6', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-720-001', title: 'Training Record', level: 'D1', relevantClauses: '7.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-720-003', title: 'Employee Qualification Matrix', level: 'D1', relevantClauses: '7.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-730-001', title: 'Communication Matrix', level: 'D1', relevantClauses: '7.4', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-810-002', title: 'Customer Requirements Log', level: 'D1', relevantClauses: '8.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-820-003', title: 'Approved Supplier List', level: 'D1', relevantClauses: '8.4', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-822-001', title: 'Supplier Performance Report', level: 'D1', relevantClauses: '8.4', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-825-002', title: 'Capacity Planning Worksheet', level: 'D1', relevantClauses: '8.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-840-002', title: 'Traceability Lot-Traveller', level: 'D1', relevantClauses: '8.5.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-845-002', title: 'Project Status Report', level: 'D1', relevantClauses: '8.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-850-002', title: 'Shelf-Life Control Log', level: 'D1', relevantClauses: '8.5.4', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-850-003', title: 'Material Handling Training Record', level: 'D1', relevantClauses: '8.5.4', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-003', title: 'Shop Traveller / Router', level: 'D1', relevantClauses: '8.5.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-005', title: 'Tool Change Record', level: 'D1', relevantClauses: '8.5.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-006', title: 'CNC Program Version Control Log', level: 'D1', relevantClauses: '8.5.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-853-001', title: 'Customer Property Log / Control Record', level: 'D1', relevantClauses: '8.5.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-853-002', title: 'Customer Tool/Fixture Register', level: 'D1', relevantClauses: '8.5.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-855-001', title: 'Post-Delivery Feedback / Service Log', level: 'D1', relevantClauses: '8.5.5', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-858-001', title: 'Software Validation Record', level: 'D1', relevantClauses: '7.1.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-870-003', title: 'MRB (Material Review Board) Minutes', level: 'D1', relevantClauses: '8.7', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-900-001', title: 'KPI Dashboard Sheet', level: 'D1', relevantClauses: '9.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-900-002', title: 'Process Performance Report', level: 'D1', relevantClauses: '9.1', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-920-002', title: 'Audit Schedule', level: 'D1', relevantClauses: '9.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-920-003', title: 'Auditor Qualification Record', level: 'D1', relevantClauses: '9.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-930-001', title: 'Management-Review Minutes', level: 'D1', relevantClauses: '9.3', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-950-002', title: 'Corrective Action Log / Register', level: 'D1', relevantClauses: '10.2', docType: 'log', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-960-002', title: 'Continuous Improvement Log', level: 'D1', relevantClauses: '10.3', docType: 'log', filePath: '/docs/placeholder.txt' },

  // LEVEL D2 - One-Time Forms
  { docId: 'FRM-440-001', title: 'Process Definition Record / Turtle Diagram', level: 'D2', relevantClauses: '4.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-630-001', title: 'Change Request Form', level: 'D2', relevantClauses: '6.3', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-710-001', title: 'Infrastructure Requirements Assessment', level: 'D2', relevantClauses: '7.1.3', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-715-003', title: 'Gage R&R Results Form', level: 'D2', relevantClauses: '7.1.5', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-720-002', title: 'Training Needs Assessment', level: 'D2', relevantClauses: '7.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-720-004', title: 'Training Effectiveness Evaluation', level: 'D2', relevantClauses: '7.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-810-001', title: 'Contract / Drawing Review Checklist', level: 'D2', relevantClauses: '8.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-815-001', title: 'Work Transfer Checklist/Approval', level: 'D2', relevantClauses: '8.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-820-001', title: 'Purchase Order Request', level: 'D2', relevantClauses: '8.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-820-002', title: 'Supplier Evaluation & Re-approval Record', level: 'D2', relevantClauses: '8.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-825-001', title: 'Production Planning Form', level: 'D2', relevantClauses: '8.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-831-001', title: 'Special Process Approval Form', level: 'D2', relevantClauses: '8.5.1.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-832-001', title: 'Counterfeit Part Risk Assessment', level: 'D2', relevantClauses: '8.1.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-840-001', title: 'Material Identification Tag', level: 'D2', relevantClauses: '8.5.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-842-001', title: 'FOD Prevention Checklist', level: 'D2', relevantClauses: '8.5.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-842-002', title: 'Housekeeping/5S Audit Form', level: 'D2', relevantClauses: '8.5.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-845-001', title: 'Project Plan Template', level: 'D2', relevantClauses: '8.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-850-001', title: 'Storage Area Inspection Checklist', level: 'D2', relevantClauses: '8.5.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-850-004', title: 'Preservation / Packaging Checklist', level: 'D2', relevantClauses: '8.5.4', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-001', title: 'Operation Sheet', level: 'D2', relevantClauses: '8.5.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-002', title: 'Process Validation Report', level: 'D2', relevantClauses: '8.5.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-851-004', title: 'Machine Setup Verification Checklist', level: 'D2', relevantClauses: '8.5.1', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-852-001', title: 'First Article Inspection Report (FAIR)', level: 'D2', relevantClauses: '8.5.1.3', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-855-002', title: 'Customer Satisfaction Survey', level: 'D2', relevantClauses: '8.5.5', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-860-001', title: 'Final Inspection Report', level: 'D2', relevantClauses: '8.6', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-860-002', title: 'Dimensional Inspection Data Sheet', level: 'D2', relevantClauses: '8.6', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-860-003', title: 'Certificate of Conformance', level: 'D2', relevantClauses: '8.6', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-860-004', title: 'Test Data Records', level: 'D2', relevantClauses: '8.6', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-870-001', title: 'Non-conformance Report (NCR)', level: 'D2', relevantClauses: '8.7', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-870-002', title: 'Disposition Decision Record', level: 'D2', relevantClauses: '8.7', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-920-001', title: 'Internal Audit Plan & Report', level: 'D2', relevantClauses: '9.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-930-002', title: 'Management Review Input Data Summary', level: 'D2', relevantClauses: '9.3', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-950-001', title: 'Corrective Action Request (CAR)', level: 'D2', relevantClauses: '10.2', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-952-001', title: 'Human Factors Assessment Form', level: 'D2', relevantClauses: '10.2.1.b', docType: 'form', filePath: '/docs/placeholder.txt' },
  { docId: 'FRM-960-001', title: 'Improvement Project Form', level: 'D2', relevantClauses: '10.3', docType: 'form', filePath: '/docs/placeholder.txt' },
];

export const getDocumentsByLevel = () => {
  const levels: QualitySystemDocument['level'][] = ['A', 'B', 'C', 'D1', 'D2'];
  const groupedDocs: Record<QualitySystemDocument['level'], QualitySystemDocument[]> = {
    A: [], B: [], C: [], D1: [], D2: []
  };

  qualitySystemDocuments.forEach(doc => {
    if (groupedDocs[doc.level]) {
      groupedDocs[doc.level].push(doc);
    }
  });
  return groupedDocs;
};

export const levelTitles: Record<QualityDocumentLevel, string> = {
  A: "LEVEL A - MANUAL & POLICIES",
  B: "LEVEL B - CORE PROCEDURES",
  C: "LEVEL C - WORK INSTRUCTIONS",
  D1: "LEVEL D1 - CONTINUOUS LOGS",
  D2: "LEVEL D2 - ONE-TIME FORMS",
};
